# This blueprint deploys your application using a Docker container.
# The Docker service will handle both the backend logic and serving the static frontend files.
services:
  - type: docker
    name: data-analyst-agent
    # This is the root directory of your project where the Dockerfile is located.
    rootDir: .
    # The Dockerfile handles all build commands and dependencies.
    # The startCommand is also defined in the Dockerfile, making this file simpler.
    envVars:
      - key: APIPE_API_KEY # Your LLM API key.
        sync: false
      - key: PYTHON_VERSION
        value: "3.12.0"
